sudo: false  # Use container-based infrastructure
language: python
python:
  - "2.7"
  - "3.6"
env:
  - KERAS_BACKEND=tensorflow
cache:
  pip: true
  # cache directory used for Ensembl downloads of GTF and FASTA files
  # along with the indexed db of intervals and ID mappings and pickles
  # of sequence dictionaries. Also, pip
before_install:
  # download different versions of mini-conda for py2 vs. py3
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # reset the shell's lookup table for program name to path mappings
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - python --version
install:
  - >
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
      numpy scipy nose pandas pandoc
  - source activate test-environment
  - pip install pypandoc pylint
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
script:
  - ./lint.sh
  - nosetests test --with-coverage --cover-package=pepdata
after_success:
  coveralls
deploy:
  provider: pypi
  user: openvax
  distributions: sdist
  password:
    secure: "hCHGiwfN7erIjis4UVnEjmxpoj0kd2cCu46frjtKfTL26F3r7/ulwq+0IOTsV1bGt1H3URuRYUSHjVjMHoeBX3FEZ4A+w1BldnfqJGKtg9wRcyWUNI56d1awgXQ/rJwfL3DQSFeibBbm80F7Evw2ZrlPkX0Q8ckAuBLcege842I="
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
